# .github/workflows/main.yml
name: Fetch Currency Rates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  fetch-rates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Fetch currency rates
      run: go run ./src/main.go

    - name: Commit and push if changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Update currency rates" -a || echo "No changes to commit"
        git push
